db_name = "example.db"
table_yachts = "yachts"
yacht_id = "id"
yacht_type = "type"
yacht_price = "price"
yacht_rate = "rate"
yacht_seat = "seat"
yacht_description = "description"
yacht_pdf = "pdf"


table_photos = "photos"
photo_id = "id"
photo_yachtid = "yacht_id"
photo_link = "link"

table_orders = "orders"
order_id = "id"
order_yacht = "yacht_id"
order_startdate = "startdate"
order_finishdate = "finishdate"
order_peoplecount = "people"
order_id = "id"
order_services = "services"

table_services = "services"
service_id = "id"
service_price = "price"
service_title = "title"
service_isstuff = "stuff"

table_built = "built_in"
built_id = "id"
built_title = "title"

table_order_service = "order_service"
order_service_id = "id"
order_service_serviceid = "serviceid"
order_service_orderid = "orderid"

table_yacht_built = "yacht_built"
yacht_built_id = "id"
yacht_built_builtid = "serviceid"
yacht_built_yachtid = "orderid"
